# Generated by Django 3.0.3 on 2021-04-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsweb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
